### ISSUE TITLE
Separator not centered with atom-material-ui

### ISSUE THREAD

**Issue by mrleblanc101** [atom-community/tool-bar#206]
Hi,
Toolbar separator are not center and are too dim using atom-material-ui (see screenshot).
I had to add this to my stylesheet to have the expected behavior: 
```css:
.amu-compact-tab-bar .tool-bar.tool-bar-16px.tool-bar-vertical .tool-bar-spacer,
.amu-compact-tab-bar .tool-bar.tool-bar-24px.tool-bar-vertical .tool-bar-spacer,
.amu-compact-tab-bar .tool-bar.tool-bar-32px.tool-bar-vertical .tool-bar-spacer {
    margin: 0 auto;
    border-color: rgba(131, 148, 150, 0.65);
}
```
<img width="42" alt="capture d ecran 2017-10-14 a 22 51 15" src="https://user-images.githubusercontent.com/17392251/31581171-3a9afe8c-b132-11e7-9dbd-3a44bd1cc66a.png">
<img width="41" alt="capture d ecran 2017-10-14 a 22 51 52" src="https://user-images.githubusercontent.com/17392251/31581172-4ac06f4a-b132-11e7-9829-5c9b32339ca6.png">
